---

- hosts: all
  roles:
    - fetch-artifacts

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_pulp }}"

- hosts: "{{ site_pulp.fqdn }}"
  roles:
    - contrail-common-libs2
    - upload-artifacts

