---

- name: show the list of running containers
  command: 'docker ps -a'
  become: true

- name: show processes
  command: 'ps aux --sort rss'

- name: show memory usage
  command: 'free -m'

- name: (hack) Wait for the vrouter initialization
  action: 'shell ip route | grep vhost0'
  become: true
  delay: 20
  register: vhost_interface
  retries: 30
  until: vhost_interface.stdout != ""
  when:
    - inventory_hostname in groups['data-plane']
    - cloud_orchestrator == 'openstack'

- name: check interfaces for addresses
  command: 'ip addr'
  become: true
