---

- name: Prepare packaging variable
  contrail_packaging:
    zuul: "{{ zuul }}"
    release_type: "nightly"

- name: Print the packaging variables
  debug:
    var: packaging

- name: Separate the numbering sequences by each pipeline, but leave it alone for legacy pipelines
  set_fact:
    version_for_build_numbering: "{{ packaging.version.public   if zuul.pipeline != 'periodic-nightly-test' else   packaging.version.public + '-' + zuul.pipeline }}"

- name: Generate the build number
  build_number:
    zuul_buildset_id: "{{ zuul.buildset }}"
    version: "{{ version_for_build_numbering }}"
    build_cache_db_connection_info: "{{ build_cache_db }}"

- name: Print the generated build number
  debug:
    var: build_number

- name: Save the generated build number for subsequent jobs in the pipeline
  zuul_return:
    data:
      build_number: "{{ build_number }}"
