---

- hosts: localhost
  roles:
    - role: add-fileserver
      fileserver: "{{ site_logs }}"
    - emit-ara-html

- hosts: "{{ site_logs.fqdn }}"
  gather_facts: false
  roles:
    - role: upload-logs
      zuul_log_url: "http://192.168.14.15"

- hosts: "{{ site_logs.fqdn }}"
  roles:
    - role: end-of-post-logs

