---

- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.opencontrail.org"

- hosts: all
  roles:
    - disable-os-unattended-upgrades
    - add-build-sshkey
    - clean-last-build
    - configure-hosts-entries
    - role: configure-mirrors
      mirror_fqdn: "us.archive.ubuntu.com"
      pypi_mirror: "https://pypi.python.org/pypi"
      wheel_mirror: "https://pypi.python.org/wheel/ubuntu-16.04-x86_64"
    - role: configure-maven-proxy
      #maven_repo_mirror_url: 'http://{{ nexus.fqdn }}/repository/{{ nexus.repos.maven }}/'
      maven_repo_mirror_url: 'https://repo.maven.apache.org/maven2/'
    - validate-host
    - prepare-workspace
    - gitlog-upload

