---

- name: Set the facts for Nexus docker registry location
  set_fact:
    nexus_registry_fqdn: '{{ nexus.fqdn }}'
    nexus_registry_port: '{{ nexus.registry.tungsten_ci }}'

- name: Nightly pipeline uses separate registry location
  set_fact:
    nexus_registry_port: '{{ nexus.registry.tungsten_nightly }}'
  when: zuul.pipeline | regex_search('^periodic-nightly')

- name: Save registry location to a file on executor
  copy:
    content: '{{ {"registry_port": nexus_registry_port } | to_nice_yaml }}'
    dest: '{{ zuul.executor.work_root }}/saved_vars.yaml'
  delegate_to: localhost

- name: Return registry location back to zuul for children jobs
  zuul_return:
    data:
      docker_registry_port: '{{ nexus_registry_port }}'
      contrail_docker_registry: '{{ nexus_registry_fqdn }}:{{ nexus_registry_port }}'
  delegate_to: localhost
