---

hosts_entries:
  - fqdn: mirror.regionone.jnpr-contrail-ci.opencontrail.org
    address: 10.84.56.27
  - fqdn: mirror.regionone.jnpr-contrail-ci-c.opencontrail.org
    address: 10.84.56.27
  - fqdn: repo01-jnpr.opencontrail.org
    address: 107.170.203.108

