---

- name: Add review.opencontrail.org remote
  command: git remote add gerrit "http://gerrit.mcp.mirantis.com:29418/{{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/src/gerrit-us2.mcp.mirantis.net/{{ item }}"
  failed_when: false
  with_items:
    - contrail/contrail-controller
    - contrail/contrail-build
    - contrail/contrail-vrouter
    - contrail/contrail-sandesh
    - contrail/contrail-generateDS
    - contrail/contrail-common
    - contrail/contrail-analytics
    - contrail/contrail-api-client
  tags:
    # Ignore ANSIBLE0006: Can not use git module for adding remotes
    - skip_ansible_lint

- name: Remove wrong empty remote
  command: git remote rm origin
  args:
    chdir: "{{ ansible_env.HOME }}/src/gerrit-us2.mcp.mirantis.net/{{ item }}"
  with_items:
    - contrail/contrail-controller
    - contrail/contrail-build
    - contrail/contrail-vrouter
    - contrail/contrail-sandesh
    - contrail/contrail-generateDS
    - contrail/contrail-common
    - contrail/contrail-analytics
    - contrail/contrail-api-client

- name: Fetch all remotes
  command: git fetch --all
  args:
    chdir: "{{ ansible_env.HOME }}/src/gerrit-us2.mcp.mirantis.net/{{ item }}"
  with_items:
    - contrail/contrail-controller
    - contrail/contrail-build
    - contrail/contrail-vrouter
    - contrail/contrail-sandesh
    - contrail/contrail-generateDS
    - contrail/contrail-common
    - contrail/contrail-analytics
    - contrail/contrail-api-client
  tags:
    # Ignore ANSIBLE0006: Can not use git module for fetching
    - skip_ansible_lint
