---

- name: Add review.opencontrail.org remote
  command: git remote add gerrit "https://{{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/src/{{ item }}"
  failed_when: false
  with_items:
    - review.opencontrail.org/Juniper/contrail-controller
    - review.opencontrail.org/Juniper/contrail-build
    - review.opencontrail.org/Juniper/contrail-vrouter
    - review.opencontrail.org/Juniper/contrail-sandesh
    - review.opencontrail.org/Juniper/contrail-generateDS
    - review.opencontrail.org/Juniper/contrail-common
    - review.opencontrail.org/Juniper/contrail-analytics
    - review.opencontrail.org/Juniper/contrail-api-client
  tags:
    # Ignore ANSIBLE0006: Can not use git module for adding remotes
    - skip_ansible_lint

- name: Fetch all remotes
  command: git fetch --all
  args:
    chdir: "{{ ansible_env.HOME }}/src/{{ item }}"
  with_items:
    - review.opencontrail.org/Juniper/contrail-controller
    - review.opencontrail.org/Juniper/contrail-build
    - review.opencontrail.org/Juniper/contrail-vrouter
    - review.opencontrail.org/Juniper/contrail-sandesh
    - review.opencontrail.org/Juniper/contrail-generateDS
    - review.opencontrail.org/Juniper/contrail-common
    - review.opencontrail.org/Juniper/contrail-analytics
    - review.opencontrail.org/Juniper/contrail-api-client
  tags:
    # Ignore ANSIBLE0006: Can not use git module for fetching
    - skip_ansible_lint

